version: "3.8"
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    env_file:
      - .env
    expose:
      - "5432"
  app:
    build:
      context: .
      args:
        BUILD_ENV: ${BUILD_ENV:-}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
